from dataclasses import dataclass

@dataclass
class Config:
    model_name: str = "google/gemma-3-12b"
    dataset_name: str = "felixZzz/numina_162k_olympiads_problems"
    max_length: int = 1024
    batch_size: int = 1
    grad_accum: int = 4
    lr: float = 1e-5
    epochs: int = 2
    lora_r: int = 4
    lora_alpha: int = 16
    lora_dropout: float = 0.05
    eval_steps: int = 200
    # GRPO-specific
    grpo_lr: float = 1e-6
    num_generations: int = 4
    max_completion_length: int = 512
    # Logging
    wandb_project: str = "llm-finetuning"
    wandb_run_name: str = ""  # auto-generated by wandb if empty

